### ISSUE TITLE
Структура проектов

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#1]
Стандартная структура для такого проекта (хотя это можно и отнести к другим заданиям):
Папка с исходниками
Папка с результатами работы вебпака
Всякие конфиги в корне.

Сейчас, если я правильно понимаю, у тебя для каждого проекта есть отдельный репозиторий под разработку и отдельный репозиторий под результат. Это крайне неудобно

**Comment by mrNemoZero** [comment]
Да просто из всех вариантов выложить на гитпейдж из того же репозитория,подходит это только создать docs и в нем результат хранить,у меня он пока отказывается смотреть только с нее,не понимаю пока почему. В остальных получается структура проекта нарушиться ведь?

**Comment by mrNemoZero** [comment]
Добавил папку res с результатом вэбпака и в редми написал как на страницу попасть

**Comment by mrNemoZero** [comment]
А мне самому закрывать ишью? Или как проверишь закроешь сам?

**Comment by Zarwlar** [comment]
Закрывай, если считаешь выполненным. Я потом проверю
