### ISSUE TITLE
index.pug не по БЭМ

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#11]
Если кажется, что без "элементов элементов" не обойтись, то лучше подумать над названиями

**Comment by mrNemoZero** [comment]
А можно плиз подробней?) По БЭМ у компонентов не должно быть внешних отступов, я создал в index.pug блоки для позиционирования компонентов и обернул ими компоненты. В названиях присутствует положение на сайте и имя компонента,что бы понятней было,какой компонент обернут

**Comment by Zarwlar** [comment]
Суть в том, что у тебя есть контейнер, но у него нет элементов, хотя они, по идее, ими являются левые и правые колонки

**Comment by mrNemoZero** [comment]
Commit c4fb5e6
