### ISSUE TITLE
font-family

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/maket-1#13]
`font-family MyriadPro, Helvetica, Arial, sans-serif` посмотри еще раз пример в стандартах. У тебя щас 2 подключаемых нестандартных шрифта: "MyriadPro" и  "Helvetica" и последний как я понимаю просто скопипастен из примера в стандартах и в проекте его нет.

**Comment by mrNemoZero** [comment]
Да это я необдуманно скопипастил

**Comment by mrNemoZero** [comment]
Commit c740545
