### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#14]
У profile голый текст, хотя одна его часть должна быть выделена жирным шрифтом

**Comment by mrNemoZero** [comment]
Прочитал в риззоме "**..в обычных проектах прямо в тексте просто html зашит, а текст такой откуда-нибудь из админки прилетает, где его в WYSIWYG редакторе манагеры правят"** .
Поэтому подумал так оставить,хорошо переделаю

**Comment by Zarwlar** [comment]
В целом - да, но здесь лучше самому это оформить

**Comment by mrNemoZero** [comment]
Commit 0005958
