### ISSUE TITLE
block-header__image_*

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#15]
Избавиться от этих модификаторов

**Comment by Zarwlar** [comment]
Хотя можно оставить, но нужно удалить лишние файлы со спрайтами

**Comment by mrNemoZero** [comment]
Так там один файл только, он правда назван был sprites1.png переименовал щас назван sprites.png

**Comment by mrNemoZero** [comment]
Ой, извиняюсь проглядел(
