### ISSUE TITLE
У одного блока два элемента

### ISSUE THREAD

**Issue by shevdi** [mrNemoZero/maket-1#16]
По БЭМ у блока может быть только один элемент. При необходимости можно объединять два элемента в один.
Например,  `.contact__table__cell` можно переделать на `.contact__table-cell`
Модификатор тоже должен быть один. При необходимости можно назначить просто два класса. Например, у тебя есть `.list-item__name_color_black`. Это выглядит как два модификатора )

**Comment by mrNemoZero** [comment]
Commit a792048 fixes #16

**Comment by mrNemoZero** [comment]
Блин не туда)я только щас узнал про то что можно было при коммите указывать ишью,и автоматом сюда уведомление прийдет. А больше половины ишью уже исправил

**Comment by mrNemoZero** [comment]
Commit a792048

**Comment by mrNemoZero** [comment]
По поводу ".list-item__name_color_black. Это выглядит как два модификатора )". Это я делал как ключ-значение, в БЭМ такое есть. Но я все равно переделал)
![key-value](https://user-images.githubusercontent.com/16408935/31383973-41941b68-ade7-11e7-80a1-4c829d8f358a.JPG)

**Comment by shevdi** [comment]
Хорошо. Моя ошибка. Совсем забыл, что такое есть.
