### ISSUE TITLE
Проверка длинных имен

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-1#19]
![image](https://user-images.githubusercontent.com/2928964/31725974-dd5ee14a-b44f-11e7-9747-7a1179270c83.png)

захардкодил бессовестно стили под конкретные текстовые значения, чуть-чуть контент другой и все ползет :)

**Comment by mrNemoZero** [comment]
а как вот правильно?)Слишком длинный текст не должен двигать справа текст, а длинный текст как вести себя должен, обрезаться?Просто ечли переноситься вниз, то снизу текст двигать будет, это же тоже не правильно?)

**Comment by Znack** [comment]
Ну как минимум не должна у текста вторая строка слазить левее, чем верхняя. Это у тебя все из-за кривых маржинов, когда ты пытался выровнять тексты из-за кружка черного слева. Подумай, как красиво сделать всю эту композицию, которая бы хорошо обрабатывала любой текст, чтобы он не налазил на этот отсуп, который занимает черный круг

**Comment by mrNemoZero** [comment]
Ну весть текст (степень, дату, университет и описание)еще в один блок объединил, так что теперь они перемещаются на другую строку норм
![screen111](https://user-images.githubusercontent.com/16408935/31754558-a992d510-b4c2-11e7-8ae4-7b379a9777ff.png)
