### ISSUE TITLE
Все параметры передавать из корневой страницы 

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-1#22]
Сейчас у тебя contacts задаются в корне массивом и передаются дальше в миксин, так в идеале для всего сделать, потому что в реальных проектах шаблонизаторы так и работают — получают сверху полный набор данных (контекст для рендеринга) и его уже раскидывают по всей иерархии

**Comment by mrNemoZero** [comment]
Если к проекту добавлю еще папку типа "data" и там буду хранить в формате json данные и уже в index буду загружать оттуда,то норм?

**Comment by Znack** [comment]
Да, будет вообще огонь :) Но это непросто :)

**Comment by mrNemoZero** [comment]
Так теперь мне кажется я че то не то делаю,у меня получилось сделав тае:
-var contacts = require("./data/contact.json")
И использовать уже таким образом. В data у меня массив из входящих данных в json забит
+contact(contacts.data)

**Comment by Znack** [comment]
Гуд :)

только лучше одним файлом. И у тебя содержимое не должно быть обязательно той же структурой. По идее там будет такая структура, которая сами сущности хорошо описывает, как будто в базе данных. У тебя же бд не знает про верстку и не должна подстраиваться под нее? :)

**Comment by mrNemoZero** [comment]
А я наоборот подумал разнести будет лучше на отдельные. Посмотрел просто в примере в доп. источниках сложной js игры и там все json разнесены) Хотя это конечно не страница,но на нее ориентировался)

**Comment by mrNemoZero** [comment]
Я только объединил в один файл. структуру я не понял надо переделать все же?
Я так для удобствва только, я понимаю,что структура будет другой в базе))

**Comment by Znack** [comment]
Ну окей, оставь пока. Просто было бы полезным опытом еще понимать, что структура данных и структура верстки чаще всего различна. И уметь всегда структуру данных самих независимо прорабатывать
