### ISSUE TITLE
Странный БЭМ

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-1#23]
Это элемент в элементе`contact__table__row__cell`? :)

Просто элементы еще можно в html друг в друга вкладывать, но в цсс в классах у тебя нет показателя вложенности эементов

**Comment by mrNemoZero** [comment]
А я вот просто неправильно​ понял наверное.Так нельзя разве, просто ячейка без строки не может существовать,поэтому она как бы часть элемента row. 
Хотя тут у меня лишний тег вообще

**Comment by mrNemoZero** [comment]
АА кажется понял, т.е. их по идее надо было на два элемента разделить **contact__table__row** И **contact__table__cell**?)

**Comment by Znack** [comment]
Да-да, у тебя в стилях должна быть плоская структура (какой она как раз сейчас в новом коммите и стала). То есть буквально уровня три-четыре максимум (block->element -> modificator -> @media)
а не  (block -> element -> element -> element -> @media -> element -> modificator -> @media) 😆

**Comment by mrNemoZero** [comment]
ну  я тогда еще все пересмотрю ко второму макету уже добавили похожее ишью, там в меня ваще Сатана вселился и я все так сделал =))
