### ISSUE TITLE
Ограничение по ширине

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#24]
Нужно поставить ограничение по ширине, иначе вёрстка будет расползаться на мониторах с большим разрешением
![image](https://user-images.githubusercontent.com/26929933/31727370-9d791402-b453-11e7-9137-5b1c6d20b9ea.png)

**Comment by mrNemoZero** [comment]
Ага, забыл про это.Ну я тогда макс ширину как у макета поставлю, норм будет?)

**Comment by Zarwlar** [comment]
Да, если я правильно понял)

**Comment by mrNemoZero** [comment]
544b22b

**Comment by mrNemoZero** [comment]
все сделал)
