### ISSUE TITLE
Перейти от px к em

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#27]
Разберись в em/rem и перейди с пикселей на эти единицы измерения)

**Comment by mrNemoZero** [comment]
А их прям везде надо использовать или только в font-size? У меня вроде font-size везде  в em

**Comment by Zarwlar** [comment]
По максимуму) Но сперва тебе нужно разобраться, какая образовывается связь между размерами шрифта и параметрами у элементов, которые заданы в em/rem

**Comment by mrNemoZero** [comment]
ну я знаю rem отнотсительно размера шрифта html, еm относительно текущего шрифта в блоке
