### ISSUE TITLE
overused <section> tag

### ISSUE THREAD

**Issue by shevdi** [mrNemoZero/maket-1#31]
По сути у тебя 7 разделов. Не вижу смысла поэтому в больше, чем семи section тэгах. Левая и правая колонки не несут никакого особого смысла. Поэтому помечать их как section излишне.

**Comment by mrNemoZero** [comment]
**<article> - независимая часть страницы, которая не теряет смысла, если ее показать пользователю отдельно 
<section> - какая-либо обособленная часть страницы, например, блок внутри сайдбара или блок баннеров после статьи**
Ну вот как то section кажется больше подходит. Или авобще их как дивы обычные использовать?

**Comment by shevdi** [comment]
У тебя получается, что по сути один блок помечен дважды, просто на разных уровнях. Ну, а две колонки на мой взгляд не несут смысловой нагрузки. Да, можно просто дивками.

**Comment by mrNemoZero** [comment]
да я подумал здесь они важны, все же две колонки в макете, а как они в уменьшенном
 виде выглядят не ясно,всмысле на маленьких экранах

**Comment by shevdi** [comment]
На счет колонок немного спорно. Но у тебя еще обернут дважды контейнер. Достаточно одного. И в хэдере еще два элемента обернуты.
