### ISSUE TITLE
Убрать whitespace

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#32]
Включи их отображение, и убери, пожалуйста) Сейчас много где есть лишние пробелы. Выполни это для всех проектов)

**Comment by mrNemoZero** [comment]
да я вроде удаляю их) Пересмотрю еще подробней)

**Comment by mrNemoZero** [comment]
Вот нашел в основном тоьлько кучу пробелов в конце строк. Сейчас только для первого макета убрал
