### ISSUE TITLE
Неправильно назван модификкатор

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#33]
В соглашениях по именованию нет такого стиля, который используешь ты)
`div(class='list-item__name list-item__name_color-'+modification) #{item.name}`

**Comment by mrNemoZero** [comment]
разве нельзя назвать модификатор color-red напрмиер?
Можно переименовать как ключ значение в БЭМ на _color_red конечно, но думал, что и так как я сделал можно(

**Comment by Zarwlar** [comment]
Нет, так нельзя) Через _color_red - ок)
