### ISSUE TITLE
Разряженность кода

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/maket-1#35]
Возьмём, к примеру, skill_points.pug
```
  -for(var i = 0; i<item.skillPoints;i++)
   .skill-points__point.skill-points__point_blue
  -for(var i =0; i < item.countPoints-item.skillPoints;i++)
   .skill-points__point
```
Обрати внимание на циклы. Где-то ты ставишь пробелы, а где-то нет.
Во все проектах должен быть выдержан единый стиль кода, который
должен содержать умеренную разряженность кода (т.е. нужно ставить
пробелы, но без фанатизма)

**Comment by mrNemoZero** [comment]
Вот ставить или нет пробелы? Просто в тегах в одном из ишью сказали не ставить пробелы например:
.divClass(data-position="1,1")
Но вот тут как бы pug-код и например airBnB для js говорит ставить пробелы?
Мне кажется, что надо ставить, т.к. тут код все же)

**Comment by Zarwlar** [comment]
Да, нужно ставить.
Т.е., например, вызов миксина с несколькими параметрами:
`example(x1, x2)`
А не
`example(x1,x2)`
Циклы
`for(var i = 0; i < 10; i++)`

**Comment by mrNemoZero** [comment]
ок, спасибо)

**Comment by Zarwlar** [comment]
Вот такую статью нашёл, должна пригодиться) https://learn.javascript.ru/coding-style

**Comment by mrNemoZero** [comment]
Спасибо0) Ну у меня linter настроен для js там вроде все более менее норм,а в  pug да могу накосячит)
