### ISSUE TITLE
Переделать header line

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/maket-1#38]
Сейчас криво сделано выравнивание вертикальное, плюс можно обойтись без overflow: hidden у родителя :)

**Comment by mrNemoZero** [comment]
Не понятный отступ снизу у шрифта, скорей всего с ним косяк, когда отключаю на странице выравнивается по центру
![image](https://user-images.githubusercontent.com/16408935/34091769-608c088c-e3f2-11e7-9097-5d54a8eb2a8d.png)

**Comment by mrNemoZero** [comment]
В итоге манипуляциями с height смог выровнять,но че то не могу больше никак отступ снизу убрать(
